project:
  type: website

website:
  description: "Final Projects for PHYS 360 during Fall 2025"
  site-url: https://kdruck.com/fp-f25
  title: "Final Projects Fall 2025"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/phys360/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



